## Numpy
- numerical python
- creating arrays and mathematical operations statistical operations

In [1]:
# importing numpy
import numpy as np


In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [3]:
len(dir(np))

620

In [4]:
#creating an array
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [5]:
a1.ndim

1

In [6]:
a1.size

5

In [7]:
a1.shape

(5,)

In [9]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
a2.shape

(2, 5)

In [11]:
a3=np.array([[[1,2,3,4],[4,5,6,7],[8,9,0,12]]])
a3

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9,  0, 12]]])

In [13]:
a3=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [14]:
a3.ndim

1

In [15]:
a3.shape

(30,)

In [17]:
a4=a3.reshape(2,15)
a4.shape

(2, 15)

In [18]:
a3.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [26]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [25]:
a4=a3.reshape(3,10)
a4[1:2,5:6]

array([[16]])

In [27]:
a3.shape

(30,)

In [30]:
a3=np.arange(1,31)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
a4=np.arange(1,10)
a4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a5=a3.reshape(5,6)
a5[4:5,1:2]

array([[26]])

In [38]:
a5.ndim

2

In [40]:
a5.shape

(5, 6)

In [43]:
a4=a3.reshape(3,10)
a4[1:2,1::2]

array([[12, 14, 16, 18, 20]])

In [44]:
a4[0:3,1::2]

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [46]:
a5=a3.reshape(6,5)
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [49]:
a5[4:,2:4]

array([[23, 24],
       [28, 29]])

In [50]:
a5[3::2,2::2]

array([[18, 20],
       [28, 30]])

In [53]:
a5[0::5,1::3]

array([[ 2,  5],
       [27, 30]])

In [54]:
np.random.random()

0.9608511278259936

In [55]:
np.random.rand()

0.6294506977815614

In [56]:
np.random.rand(1,10)

array([[0.86187557, 0.52991632, 0.34647779, 0.77689544, 0.85892757,
        0.24621053, 0.8599848 , 0.12913122, 0.23083961, 0.89869721]])

In [57]:
np.random.randn(1,10)

array([[ 0.69559024,  0.10880089,  1.29185877,  0.6293873 , -0.71335623,
         0.11443535,  1.10796403, -0.53660107, -1.42360773,  2.03948809]])

In [58]:
np.random.randint(91,100,100)

array([93, 94, 94, 98, 92, 97, 98, 97, 93, 96, 91, 97, 97, 96, 92, 94, 94,
       94, 99, 95, 97, 99, 97, 95, 94, 93, 97, 97, 97, 98, 96, 92, 95, 91,
       98, 91, 93, 99, 96, 93, 95, 93, 94, 98, 93, 93, 96, 91, 96, 98, 91,
       99, 98, 98, 91, 95, 96, 97, 95, 96, 94, 94, 98, 93, 94, 99, 93, 94,
       91, 98, 91, 95, 99, 92, 99, 91, 92, 93, 93, 94, 97, 93, 91, 92, 97,
       91, 91, 91, 97, 97, 97, 98, 91, 92, 94, 93, 99, 95, 92, 99])

In [59]:
np.random.randint(1,1000,100)

array([163,  43, 486, 128, 605, 837, 105, 450, 688, 137, 703, 577, 520,
       984, 319, 835, 887, 357, 378, 357, 941, 870, 431, 626, 208, 641,
       103, 133, 963, 255, 113, 950, 133, 276, 989, 664, 746, 421, 365,
       211, 851, 717, 377, 730, 274, 702, 426, 134, 125, 572, 839, 914,
       719, 134, 220, 326, 617, 389, 770, 402, 203, 622, 177, 500, 450,
       292, 197, 975, 321, 360, 427, 667, 144, 391, 870, 490, 718,  68,
       325, 917, 637, 672, 504, 242, 787, 486, 516, 269, 388, 216, 942,
       857, 510, 914, 727, 436, 398, 433, 186,  65])

In [60]:
np.random.randint(1,1000,5)

array([253, 548,  31, 120, 125])

In [66]:
np.random.randint(1,1000,10)

array([212, 395, 836, 134, 789, 586, 563, 810, 202,  37])

In [68]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [87]:
a6=np.random.randint(1,1000,20)
for i in a6:
    if(i%2==0):
        print(i)

502
406
34
98
678
736
942


In [90]:
a3=np.random.randint(1,100,10)
a3[a3%2==0]

array([27, 47, 77, 11, 21, 39, 27, 61])

In [96]:
a3*2

array([ 54, 104,  94, 154,  22,  42,  78,  68,  54, 122])